module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.03,True,2022-11-07T07:00:13,,
cowidev.vax.batch.australia,,,2022-11-07T07:00:10,,
cowidev.vax.batch.austria,2.12,True,2022-11-07T07:00:13,,
cowidev.vax.batch.belgium,1.92,True,2022-11-07T07:00:12,,
cowidev.vax.batch.bolivia,2.14,True,2022-11-07T07:00:13,,
cowidev.vax.batch.canada,6.59,True,2022-11-07T07:00:17,,
cowidev.vax.batch.chile,1.36,True,2022-11-07T07:00:14,,
cowidev.vax.batch.czechia,3.39,True,2022-11-07T07:00:16,,
cowidev.vax.batch.denmark,4.63,True,2022-11-07T07:00:17,,
cowidev.vax.batch.ecdc,60.07,False,2022-11-07T07:04:28,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f07bc552280>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f07bc552280>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 498, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 488, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 117, in read
    df = read_csv_from_url(self.source_url, timeout=30)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 55, in read_csv_from_url
    download_file_from_url(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 80, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f07bc552280>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f07bc552280>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))"
cowidev.vax.batch.ecuador,1.71,True,2022-11-07T07:00:15,,
cowidev.vax.batch.estonia,0.59,True,2022-11-07T07:00:16,,
cowidev.vax.batch.france,0.78,True,2022-11-07T07:00:17,,
cowidev.vax.batch.germany,2.07,True,2022-11-07T07:00:18,,
cowidev.vax.batch.greece,3.08,True,2022-11-07T07:00:20,,
cowidev.vax.batch.hong_kong,11.77,True,2022-11-07T07:00:29,,
cowidev.vax.batch.indonesia,,,2022-11-07T07:00:17,,
cowidev.vax.batch.ireland,0.8,True,2022-11-07T07:00:18,,
cowidev.vax.batch.israel,10.61,True,2022-11-07T07:00:29,,
cowidev.vax.batch.italy,10.82,True,2022-11-07T07:00:29,,
cowidev.vax.batch.japan,0.47,False,2022-11-07T07:04:29,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 236, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 220, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 156, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 88, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 97, in _read_xlsx
    xlsx = pd.ExcelFile(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1191, in __init__
    ext = inspect_excel_format(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1070, in inspect_excel_format
    with get_handle(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 214, in urlopen
    return opener.open(url, data, timeout)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 523, in open
    response = meth(req, response)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 632, in http_response
    response = self.parent.error(
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 561, in error
    return self._call_chain(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 494, in _call_chain
    result = func(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
",HTTP Error 404: Not Found
cowidev.vax.batch.jersey,0.56,True,2022-11-07T07:00:29,,
cowidev.vax.batch.latvia,18.67,True,2022-11-07T07:00:47,,
cowidev.vax.batch.lithuania,1.33,True,2022-11-07T07:00:30,,
cowidev.vax.batch.luxembourg,2.06,True,2022-11-07T07:00:31,,
cowidev.vax.batch.malaysia,0.98,True,2022-11-07T07:00:30,,
cowidev.vax.batch.malta,0.7,True,2022-11-07T07:00:31,,
cowidev.vax.batch.netherlands,,,2022-11-07T07:00:30,,
cowidev.vax.batch.new_zealand,10.35,True,2022-11-07T07:00:41,,
cowidev.vax.batch.norway,0.38,True,2022-11-07T07:00:31,,
cowidev.vax.batch.peru,4.7,True,2022-11-07T07:00:36,,
cowidev.vax.batch.portugal,,,2022-11-07T07:00:31,,
cowidev.vax.batch.romania,13.49,True,2022-11-07T07:00:45,,
cowidev.vax.batch.saudi_arabia,10.18,True,2022-11-07T07:00:46,,
cowidev.vax.batch.singapore,1.75,True,2022-11-07T07:00:42,,
cowidev.vax.batch.slovakia,39.97,True,2022-11-07T07:01:22,,
cowidev.vax.batch.slovenia,1.36,True,2022-11-07T07:00:46,,
cowidev.vax.batch.south_korea,38.81,True,2022-11-07T07:01:25,,
cowidev.vax.batch.spc,16.06,True,2022-11-07T07:01:02,,
cowidev.vax.batch.sweden,91.7,False,2022-11-07T09:35:51,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/sweden.py"", line 244, in main
    Sweden().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/sweden.py"", line 238, in export
    df = self.read().pipe(self.pipeline)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/sweden.py"", line 144, in pipeline
    .pipe(make_monotonic)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 44, in make_monotonic
    raise Exception(
Exception: 51 rows have been removed. That is more than maximum allowed (10) by make_monotonic() - check the data. Check 
          date location                                         source_url                                            vaccine  total_vaccinations  people_vaccinated  people_fully_vaccinated  total_boosters
46  2021-11-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            15113941            7392904                  6925338            <NA>
47  2021-11-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            15518775            7436125                  6990165            <NA>
48  2021-11-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            15946494            7481621                  7067100            <NA>
49  2021-12-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            16380538            7527821                  7138275            <NA>
50  2021-12-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            16848925            7575290                  7209137            <NA>
51  2021-12-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            17386583            7618376                  7272440            <NA>
52  2021-12-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            17616119            7635934                  7298643            <NA>
53  2022-01-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            17767320            7647865                  7315934            <NA>
54  2022-01-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            18002788            7663644                  7343045            <NA>
55  2022-01-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            18475717            7689283                  7396733            <NA>
56  2022-01-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            19023097            7712221                  7440722            <NA>
57  2022-01-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            19491083            7727178                  7467530            <NA>
58  2022-02-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            19881289            7737427                  7488672            <NA>
59  2022-02-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20179002            7745739                  7510002            <NA>
60  2022-02-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20379636            7751754                  7527206            <NA>
61  2022-02-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20545073            7756652                  7541261            <NA>
62  2022-03-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20686930            7760224                  7550484            <NA>
63  2022-03-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            20820749            7763294                  7557824            <NA>
64  2022-03-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            20991918            7767318                  7565207            <NA>
65  2022-03-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21108967            7770139                  7570543            <NA>
66  2022-04-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21201701            7772618                  7574808            <NA>
67  2022-04-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21406125            7774842                  7578286            <NA>
68  2022-04-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21595456            7776652                  7581086            <NA>
69  2022-04-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21811687            7778812                  7584266            <NA>
70  2022-05-01   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22034019            7781099                  7587569            <NA>
71  2022-05-08   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22200561            7783368                  7590490            <NA>
72  2022-05-15   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22330884            7785718                  7593510            <NA>
73  2022-05-22   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22435712            7787923                  7596641            <NA>
74  2022-05-29   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22505399            7789604                  7599524            <NA>
75  2022-06-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22567445            7791181                  7602506            <NA>
76  2022-06-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22612181            7792252                  7604892            <NA>
77  2022-06-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22653194            7793464                  7607409            <NA>
78  2022-06-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22679135            7794366                  7609221            <NA>
79  2022-07-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22705792            7795346                  7610930            <NA>
80  2022-07-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22730569            7796325                  7612308            <NA>
81  2022-07-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22759122            7797439                  7613615            <NA>
82  2022-07-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22780006            7798349                  7614651            <NA>
83  2022-07-31   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22799424            7799249                  7615536            <NA>
84  2022-08-07   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22817386            7800196                  7616417            <NA>
85  2022-08-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22833964            7801148                  7617435            <NA>
86  2022-08-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22852425            7802000                  7618460            <NA>
87  2022-08-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22880025            7802736                  7619252            <NA>
88  2022-09-04   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23050990            7803591                  7620225            <NA>
89  2022-09-11   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23371659            7804759                  7621308            <NA>
90  2022-09-18   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23683669            7805943                  7622495            <NA>
91  2022-09-25   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23990604            7807074                  7623644            <NA>
92  2022-10-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24260220            7808163                  7624819            <NA>
93  2022-10-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24469813            7809028                  7625864            <NA>
94  2022-10-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24641177            7809837                  7626821            <NA>
95  2022-10-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24778109            7810530                  7627737            <NA>
96  2022-10-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24884326            7811112                  7628588            <NA>
","51 rows have been removed. That is more than maximum allowed (10) by make_monotonic() - check the data. Check 
          date location                                         source_url                                            vaccine  total_vaccinations  people_vaccinated  people_fully_vaccinated  total_boosters
46  2021-11-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            15113941            7392904                  6925338            <NA>
47  2021-11-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            15518775            7436125                  6990165            <NA>
48  2021-11-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            15946494            7481621                  7067100            <NA>
49  2021-12-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            16380538            7527821                  7138275            <NA>
50  2021-12-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            16848925            7575290                  7209137            <NA>
51  2021-12-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            17386583            7618376                  7272440            <NA>
52  2021-12-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            17616119            7635934                  7298643            <NA>
53  2022-01-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            17767320            7647865                  7315934            <NA>
54  2022-01-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            18002788            7663644                  7343045            <NA>
55  2022-01-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            18475717            7689283                  7396733            <NA>
56  2022-01-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            19023097            7712221                  7440722            <NA>
57  2022-01-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            19491083            7727178                  7467530            <NA>
58  2022-02-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            19881289            7737427                  7488672            <NA>
59  2022-02-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20179002            7745739                  7510002            <NA>
60  2022-02-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20379636            7751754                  7527206            <NA>
61  2022-02-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20545073            7756652                  7541261            <NA>
62  2022-03-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech            20686930            7760224                  7550484            <NA>
63  2022-03-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            20820749            7763294                  7557824            <NA>
64  2022-03-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            20991918            7767318                  7565207            <NA>
65  2022-03-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21108967            7770139                  7570543            <NA>
66  2022-04-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21201701            7772618                  7574808            <NA>
67  2022-04-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21406125            7774842                  7578286            <NA>
68  2022-04-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21595456            7776652                  7581086            <NA>
69  2022-04-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            21811687            7778812                  7584266            <NA>
70  2022-05-01   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22034019            7781099                  7587569            <NA>
71  2022-05-08   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22200561            7783368                  7590490            <NA>
72  2022-05-15   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22330884            7785718                  7593510            <NA>
73  2022-05-22   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22435712            7787923                  7596641            <NA>
74  2022-05-29   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22505399            7789604                  7599524            <NA>
75  2022-06-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22567445            7791181                  7602506            <NA>
76  2022-06-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22612181            7792252                  7604892            <NA>
77  2022-06-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22653194            7793464                  7607409            <NA>
78  2022-06-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22679135            7794366                  7609221            <NA>
79  2022-07-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22705792            7795346                  7610930            <NA>
80  2022-07-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22730569            7796325                  7612308            <NA>
81  2022-07-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22759122            7797439                  7613615            <NA>
82  2022-07-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22780006            7798349                  7614651            <NA>
83  2022-07-31   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22799424            7799249                  7615536            <NA>
84  2022-08-07   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22817386            7800196                  7616417            <NA>
85  2022-08-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22833964            7801148                  7617435            <NA>
86  2022-08-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22852425            7802000                  7618460            <NA>
87  2022-08-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            22880025            7802736                  7619252            <NA>
88  2022-09-04   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23050990            7803591                  7620225            <NA>
89  2022-09-11   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23371659            7804759                  7621308            <NA>
90  2022-09-18   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23683669            7805943                  7622495            <NA>
91  2022-09-25   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            23990604            7807074                  7623644            <NA>
92  2022-10-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24260220            7808163                  7624819            <NA>
93  2022-10-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24469813            7809028                  7625864            <NA>
94  2022-10-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24641177            7809837                  7626821            <NA>
95  2022-10-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24778109            7810530                  7627737            <NA>
96  2022-10-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  Moderna, Novavax, Oxford/AstraZeneca, Pfizer/B...            24884326            7811112                  7628588            <NA>"
cowidev.vax.batch.switzerland,26.63,True,2022-11-07T07:01:29,,
cowidev.vax.batch.trinidad_and_tobago,1.9,True,2022-11-07T07:01:16,,
cowidev.vax.batch.ukraine,,,2022-11-07T07:01:15,,
cowidev.vax.batch.united_kingdom,5.23,False,2022-11-07T09:35:56,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/united_kingdom.py"", line 106, in main
    UnitedKingdom().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/united_kingdom.py"", line 94, in export
    df = df_base.pipe(self._filter_location, location).pipe(self.make_monotonic, max_removed_rows=45)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 149 have been NaNed for metric total_boosters. That is more than maximum allowed (45) by make_monotonic() - check the data. Check dates ['2022-09-24']
",1 chunks of lengths 149 have been NaNed for metric total_boosters. That is more than maximum allowed (45) by make_monotonic() - check the data. Check dates ['2022-09-24']
cowidev.vax.batch.united_states,17.71,True,2022-11-07T07:01:34,,
cowidev.vax.batch.uruguay,1.26,True,2022-11-07T07:01:24,,
cowidev.vax.batch.zimbabwe,0.52,True,2022-11-07T07:01:24,,
cowidev.vax.incremental.africacdc,,,2022-11-07T07:01:24,,
cowidev.vax.incremental.antigua_barbuda,,,2022-11-07T07:01:24,,
cowidev.vax.incremental.aruba,1.58,True,2022-11-07T07:01:26,,
cowidev.vax.incremental.azerbaijan,,,2022-11-07T07:01:25,,
cowidev.vax.incremental.bahrain,1.36,True,2022-11-07T07:01:26,,
cowidev.vax.incremental.bangladesh,21.1,True,2022-11-07T07:01:47,,
cowidev.vax.incremental.barbados,,,2022-11-07T07:01:26,,
cowidev.vax.incremental.brazil,0.06,True,2022-11-07T07:01:26,,
cowidev.vax.incremental.bulgaria,1.25,True,2022-11-07T07:01:27,,
cowidev.vax.incremental.china,36.19,True,2022-11-07T07:02:02,,
cowidev.vax.incremental.costa_rica,,,2022-11-07T07:01:27,,
cowidev.vax.incremental.croatia,0.15,True,2022-11-07T07:01:27,,
cowidev.vax.incremental.cuba,2.33,True,2022-11-07T07:01:30,,
cowidev.vax.incremental.curacao,0.4,True,2022-11-07T07:01:29,,
cowidev.vax.incremental.cyprus,0.81,True,2022-11-07T07:01:30,,
cowidev.vax.incremental.dominican_republic,7.53,True,2022-11-07T07:01:37,,
cowidev.vax.incremental.el_salvador,3.37,True,2022-11-07T07:01:33,,
cowidev.vax.incremental.faeroe_islands,0.46,True,2022-11-07T07:01:34,,
cowidev.vax.incremental.fiji,0.0,True,2022-11-07T07:01:34,,
cowidev.vax.incremental.finland,0.19,True,2022-11-07T07:01:34,,
cowidev.vax.incremental.gabon,,,2022-11-07T07:01:34,,
cowidev.vax.incremental.georgia,0.47,True,2022-11-07T07:01:34,,
cowidev.vax.incremental.greenland,1.27,False,2022-11-07T09:35:57,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 74, in main
    Greenland().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 61, in export
    data = self.read().pipe(self.pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 18, in read
    data = self._parse_data(soup)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 22, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 26, in _parse_data_metrics
    dose_1 = clean_count(re.search(r""Innuttaasut ([\d\.]+)"", counters[1].parent.find_all(""dd"")[-1].text).group(1))
IndexError: list index out of range
",list index out of range
cowidev.vax.incremental.guatemala,,,2022-11-07T07:01:34,,
cowidev.vax.incremental.guernsey,0.27,False,2022-11-07T09:35:58,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 61, in main
    Guernsey().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 50, in export
    data = self.read().pipe(self.pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 15, in read
    df = self.parse_data(soup)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 31, in parse_data
    ds.loc[ds[0] == ""Total doses"", 1].values[0].replace(""*"", """"),
IndexError: index 0 is out of bounds for axis 0 with size 0
",index 0 is out of bounds for axis 0 with size 0
cowidev.vax.incremental.hungary,0.96,True,2022-11-07T07:01:35,,
cowidev.vax.incremental.iceland,0.81,True,2022-11-07T07:01:36,,
cowidev.vax.incremental.india,0.89,True,2022-11-07T07:01:36,,
cowidev.vax.incremental.iran,,,2022-11-07T07:01:36,,
cowidev.vax.incremental.isle_of_man,6.38,True,2022-11-07T07:01:42,,
cowidev.vax.incremental.jamaica,2.11,True,2022-11-07T07:01:38,,
cowidev.vax.incremental.kazakhstan,13.27,True,2022-11-07T07:01:50,,
cowidev.vax.incremental.kosovo,1.27,True,2022-11-07T07:01:40,,
cowidev.vax.incremental.kyrgyzstan,1.06,True,2022-11-07T07:01:41,,
cowidev.vax.incremental.laos,2.16,True,2022-11-07T07:01:43,,
cowidev.vax.incremental.macao,30.19,False,2022-11-07T09:36:28,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 86, in main
    Macao().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 72, in export
    data = self.read()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 20, in read
    elem = driver.find_element_by_partial_link_text(""Weekly Bulletin on COVID-19"")
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 462, in find_element_by_partial_link_text
    return self.find_element(by=By.PARTIAL_LINK_TEXT, value=link_text)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""partial link text"",""selector"":""Weekly Bulletin on COVID-19""}
  (Session info: headless chrome=107.0.5304.87)

","Message: no such element: Unable to locate element: {""method"":""partial link text"",""selector"":""Weekly Bulletin on COVID-19""}
  (Session info: headless chrome=107.0.5304.87)
"
cowidev.vax.incremental.moldova,,,2022-11-07T07:01:43,,
cowidev.vax.incremental.monaco,37.78,True,2022-11-07T07:02:21,,
cowidev.vax.incremental.mongolia,0.68,True,2022-11-07T07:01:48,,
cowidev.vax.incremental.montenegro,0.1,True,2022-11-07T07:01:48,,
cowidev.vax.incremental.morocco,,,2022-11-07T07:01:48,,
cowidev.vax.incremental.myanmar,,,2022-11-07T07:01:48,,
cowidev.vax.incremental.nepal,,,2022-11-07T07:01:48,,
cowidev.vax.incremental.north_macedonia,,,2022-11-07T07:01:48,,
cowidev.vax.incremental.northern_cyprus,0.83,True,2022-11-07T07:01:48,,
cowidev.vax.incremental.paho,34.4,False,2022-11-07T09:37:02,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 191, in main
    PAHO().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 186, in export
    df = self.read().pipe(self.pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 51, in _parse_data
    driver.find_element_by_id(""tableauTabbedNavigation_tab_2"").click()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""tableauTabbedNavigation_tab_2""]""}
  (Session info: headless chrome=107.0.5304.87)

","Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""tableauTabbedNavigation_tab_2""]""}
  (Session info: headless chrome=107.0.5304.87)
"
cowidev.vax.incremental.pakistan,1.33,True,2022-11-07T07:01:52,,
cowidev.vax.incremental.philippines,,,2022-11-07T07:01:52,,
cowidev.vax.incremental.playground_mojmir,4.76,True,2022-11-07T07:01:56,,
cowidev.vax.incremental.poland,0.34,True,2022-11-07T07:01:57,,
cowidev.vax.incremental.qatar,,,2022-11-07T07:01:57,,
cowidev.vax.incremental.russia,0.53,False,2022-11-07T07:06:27,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 445, in _make_request
    six.raise_from(e, None)
  File ""<string>"", line 3, in raise_from
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 440, in _make_request
    httplib_response = conn.getresponse()
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 1349, in getresponse
    response.begin()
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 316, in begin
    version, status, reason = self._read_status()
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 285, in _read_status
    raise RemoteDisconnected(""Remote end closed connection without""
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/packages/six.py"", line 769, in reraise
    raise value.with_traceback(tb)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 445, in _make_request
    six.raise_from(e, None)
  File ""<string>"", line 3, in raise_from
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 440, in _make_request
    httplib_response = conn.getresponse()
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 1349, in getresponse
    response.begin()
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 316, in begin
    version, status, reason = self._read_status()
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 285, in _read_status
    raise RemoteDisconnected(""Remote end closed connection without""
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
cowidev.vax.incremental.saint_lucia,,,2022-11-07T07:01:57,,
cowidev.vax.incremental.serbia,6.5,True,2022-11-07T07:02:04,,
cowidev.vax.incremental.south_africa,8.06,True,2022-11-07T07:02:11,,
cowidev.vax.incremental.spain,12.55,True,2022-11-07T07:02:16,,
cowidev.vax.incremental.sri_lanka,,,2022-11-07T07:02:04,,
cowidev.vax.incremental.suriname,14.2,True,2022-11-07T07:02:18,,
cowidev.vax.incremental.taiwan,5.87,True,2022-11-07T07:02:16,,
cowidev.vax.incremental.thailand,4.28,True,2022-11-07T07:02:21,,
cowidev.vax.incremental.turkey,40.02,False,2022-11-07T09:37:42,"Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1040, in _validate_conn
    conn.connect()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x14bcb6fb0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 785, in urlopen
    retries = retries.increment(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14bcb6fb0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14bcb6fb0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14bcb6fb0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-11-07T07:02:18,,
cowidev.vax.incremental.vietnam,,,2022-11-07T07:02:18,,
cowidev.vax.incremental.who,4.6,True,2022-11-07T07:02:23,,
cowidev.vax.incremental.zambia,0.79,True,2022-11-07T07:02:21,,
