module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,15.78,True,2023-01-11T07:00:21,,
cowidev.vax.batch.australia,141.31,True,2023-01-11T07:02:27,,
cowidev.vax.batch.austria,14.31,True,2023-01-11T07:00:20,,
cowidev.vax.batch.belgium,10.45,True,2023-01-11T07:00:16,,
cowidev.vax.batch.bolivia,4.31,True,2023-01-11T07:00:10,,
cowidev.vax.batch.canada,29.75,True,2023-01-11T07:00:35,,
cowidev.vax.batch.chile,1.11,True,2023-01-11T07:00:06,,
cowidev.vax.batch.czechia,29.95,True,2023-01-11T07:00:35,,
cowidev.vax.batch.denmark,142.68,True,2023-01-11T07:02:28,,
cowidev.vax.batch.ecdc,146.15,True,2023-01-11T07:02:31,,
cowidev.vax.batch.ecuador,,,2023-01-11T07:00:05,,
cowidev.vax.batch.estonia,0.7,True,2023-01-11T07:00:06,,
cowidev.vax.batch.france,6.28,True,2023-01-11T07:00:12,,
cowidev.vax.batch.germany,0.18,True,2023-01-11T07:00:05,,
cowidev.vax.batch.greece,18.66,True,2023-01-11T07:00:24,,
cowidev.vax.batch.hong_kong,20.13,True,2023-01-11T07:00:25,,
cowidev.vax.batch.indonesia,,,2023-01-11T07:00:05,,
cowidev.vax.batch.ireland,6.79,True,2023-01-11T07:00:12,,
cowidev.vax.batch.israel,15.06,True,2023-01-11T07:00:20,,
cowidev.vax.batch.italy,8.28,True,2023-01-11T07:00:14,,
cowidev.vax.batch.japan,63.36,True,2023-01-11T07:01:09,,
cowidev.vax.batch.jersey,5.75,True,2023-01-11T07:00:11,,
cowidev.vax.batch.latvia,68.12,True,2023-01-11T07:01:13,,
cowidev.vax.batch.lithuania,6.32,True,2023-01-11T07:00:12,,
cowidev.vax.batch.luxembourg,3.18,True,2023-01-11T07:00:08,,
cowidev.vax.batch.malaysia,0.95,True,2023-01-11T07:00:06,,
cowidev.vax.batch.malta,1.14,True,2023-01-11T07:00:06,,
cowidev.vax.batch.netherlands,,,2023-01-11T07:00:05,,
cowidev.vax.batch.new_zealand,15.91,True,2023-01-11T07:00:21,,
cowidev.vax.batch.norway,0.56,True,2023-01-11T07:00:06,,
cowidev.vax.batch.peru,5.51,True,2023-01-11T07:00:11,,
cowidev.vax.batch.portugal,,,2023-01-11T07:00:05,,
cowidev.vax.batch.romania,54.08,True,2023-01-11T07:00:59,,
cowidev.vax.batch.saudi_arabia,9.52,True,2023-01-11T07:00:15,,
cowidev.vax.batch.singapore,5.19,True,2023-01-11T07:00:10,,
cowidev.vax.batch.slovakia,123.37,True,2023-01-11T07:02:09,,
cowidev.vax.batch.slovenia,3.22,True,2023-01-11T07:00:09,,
cowidev.vax.batch.south_korea,138.73,True,2023-01-11T07:02:25,,
cowidev.vax.batch.spc,27.28,True,2023-01-11T07:00:33,,
cowidev.vax.batch.sweden,18.01,True,2023-01-11T07:00:24,,
cowidev.vax.batch.switzerland,143.74,True,2023-01-11T07:02:30,,
cowidev.vax.batch.trinidad_and_tobago,3.58,True,2023-01-11T07:00:12,,
cowidev.vax.batch.ukraine,,,2023-01-11T07:00:09,,
cowidev.vax.batch.united_kingdom,16.02,True,2023-01-11T07:00:25,,
cowidev.vax.batch.united_states,142.59,True,2023-01-11T07:02:32,,
cowidev.vax.batch.uruguay,9.13,True,2023-01-11T07:00:20,,
cowidev.vax.batch.zimbabwe,1.44,True,2023-01-11T07:00:12,,
cowidev.vax.incremental.africacdc,,,2023-01-11T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2023-01-11T07:00:11,,
cowidev.vax.incremental.aruba,1.24,True,2023-01-11T07:00:12,,
cowidev.vax.incremental.azerbaijan,,,2023-01-11T07:00:12,,
cowidev.vax.incremental.bahrain,,,2023-01-11T07:00:12,,
cowidev.vax.incremental.bangladesh,41.2,True,2023-01-11T07:00:53,,
cowidev.vax.incremental.barbados,,,2023-01-11T07:00:12,,
cowidev.vax.incremental.brazil,0.75,True,2023-01-11T07:00:12,,
cowidev.vax.incremental.bulgaria,14.08,True,2023-01-11T07:00:26,,
cowidev.vax.incremental.china,39.61,True,2023-01-11T07:00:52,,
cowidev.vax.incremental.costa_rica,,,2023-01-11T07:00:12,,
cowidev.vax.incremental.croatia,1.14,True,2023-01-11T07:00:13,,
cowidev.vax.incremental.cuba,13.14,True,2023-01-11T07:00:25,,
cowidev.vax.incremental.curacao,1.13,True,2023-01-11T07:00:13,,
cowidev.vax.incremental.cyprus,3.9,True,2023-01-11T07:00:17,,
cowidev.vax.incremental.dominican_republic,22.65,False,2023-01-11T07:04:21,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,13.53,True,2023-01-11T07:00:27,,
cowidev.vax.incremental.faeroe_islands,2.31,True,2023-01-11T07:00:17,,
cowidev.vax.incremental.fiji,0.0,True,2023-01-11T07:00:16,,
cowidev.vax.incremental.finland,1.07,True,2023-01-11T07:00:17,,
cowidev.vax.incremental.gabon,,,2023-01-11T07:00:17,,
cowidev.vax.incremental.georgia,9.44,True,2023-01-11T07:00:26,,
cowidev.vax.incremental.greenland,0.18,False,2023-01-11T07:04:21,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 76, in main
    Greenland().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 63, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 17, in read
    data = self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 21, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 31, in _parse_data_metrics
    assert len(counter_1) == len(counter_2) == 1
AssertionError
",
cowidev.vax.incremental.guatemala,,,2023-01-11T07:00:17,,
cowidev.vax.incremental.guernsey,10.13,True,2023-01-11T07:00:27,,
cowidev.vax.incremental.hungary,131.5,True,2023-01-11T07:02:31,,
cowidev.vax.incremental.iceland,4.89,True,2023-01-11T07:00:24,,
cowidev.vax.incremental.india,3.69,True,2023-01-11T07:00:24,,
cowidev.vax.incremental.iran,,,2023-01-11T07:00:21,,
cowidev.vax.incremental.isle_of_man,2.91,True,2023-01-11T07:00:24,,
cowidev.vax.incremental.jamaica,9.25,True,2023-01-11T07:00:30,,
cowidev.vax.incremental.kazakhstan,6.27,True,2023-01-11T07:00:30,,
cowidev.vax.incremental.kosovo,8.22,False,2023-01-11T07:04:29,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 23, in read
    df = self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 32, in _parse_data
    soup = get_soup(link, verify=False)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,7.49,True,2023-01-11T07:00:31,,
cowidev.vax.incremental.laos,8.83,True,2023-01-11T07:00:33,,
cowidev.vax.incremental.macao,10.03,True,2023-01-11T07:00:34,,
cowidev.vax.incremental.moldova,,,2023-01-11T07:00:24,,
cowidev.vax.incremental.monaco,136.22,True,2023-01-11T07:02:41,,
cowidev.vax.incremental.mongolia,1.17,True,2023-01-11T07:00:26,,
cowidev.vax.incremental.montenegro,0.9,True,2023-01-11T07:00:26,,
cowidev.vax.incremental.morocco,,,2023-01-11T07:00:25,,
cowidev.vax.incremental.myanmar,,,2023-01-11T07:00:25,,
cowidev.vax.incremental.nepal,,,2023-01-11T07:00:25,,
cowidev.vax.incremental.north_macedonia,,,2023-01-11T07:00:25,,
cowidev.vax.incremental.northern_cyprus,5.7,True,2023-01-11T07:00:31,,
cowidev.vax.incremental.paho,137.76,False,2023-01-11T07:06:47,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 64, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 116, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,,,2023-01-11T07:00:26,,
cowidev.vax.incremental.philippines,,,2023-01-11T07:00:26,,
cowidev.vax.incremental.poland,1.63,True,2023-01-11T07:00:28,,
cowidev.vax.incremental.qatar,,,2023-01-11T07:00:26,,
cowidev.vax.incremental.russia,27.47,True,2023-01-11T07:00:54,,
cowidev.vax.incremental.saint_lucia,,,2023-01-11T07:00:26,,
cowidev.vax.incremental.serbia,0.41,False,2023-01-11T07:06:48,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 88, in main
    Serbia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 74, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 23, in read
    soup = get_soup(self.source_url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
",Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
cowidev.vax.incremental.south_africa,,,2023-01-11T07:00:27,,
cowidev.vax.incremental.spain,32.43,True,2023-01-11T07:00:59,,
cowidev.vax.incremental.sri_lanka,,,2023-01-11T07:00:27,,
cowidev.vax.incremental.suriname,15.62,True,2023-01-11T07:00:43,,
cowidev.vax.incremental.taiwan,11.05,False,2023-01-11T07:06:59,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 175, in main
    Taiwan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 161, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 35, in read
    df = self._parse_table(url_pdf)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 61, in _parse_table
    raise ValueError(""Table 1: format has changed!"")
ValueError: Table 1: format has changed!
",Table 1: format has changed!
cowidev.vax.incremental.thailand,6.6,True,2023-01-11T07:00:34,,
cowidev.vax.incremental.turkey,40.3,False,2023-01-11T07:07:39,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 414, in connect
    self.sock = ssl_wrap_socket(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File ""/usr/lib/python3.10/ssl.py"", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File ""/usr/lib/python3.10/ssl.py"", line 1071, in _create
    self.do_handshake()
  File ""/usr/lib/python3.10/ssl.py"", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/packages/six.py"", line 770, in reraise
    raise value
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Read timed out. (read timeout=20)
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Read timed out. (read timeout=20)"
cowidev.vax.incremental.united_arab_emirates,,,2023-01-11T07:00:30,,
cowidev.vax.incremental.vietnam,,,2023-01-11T07:00:30,,
cowidev.vax.incremental.who,76.77,True,2023-01-11T07:01:47,,
cowidev.vax.incremental.zambia,1.89,True,2023-01-11T07:00:33,,
