module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.38,True,2022-11-03T07:00:13,,
cowidev.vax.batch.australia,,,2022-11-03T07:00:10,,
cowidev.vax.batch.austria,2.04,True,2022-11-03T07:00:12,,
cowidev.vax.batch.belgium,1.69,True,2022-11-03T07:00:12,,
cowidev.vax.batch.bolivia,2.1,True,2022-11-03T07:00:12,,
cowidev.vax.batch.canada,6.28,True,2022-11-03T07:00:16,,
cowidev.vax.batch.chile,0.69,True,2022-11-03T07:00:12,,
cowidev.vax.batch.czechia,4.27,True,2022-11-03T07:00:16,,
cowidev.vax.batch.denmark,3.21,True,2022-11-03T07:00:15,,
cowidev.vax.batch.ecdc,31.88,True,2022-11-03T11:53:14,,
cowidev.vax.batch.ecuador,3.51,True,2022-11-03T07:00:17,,
cowidev.vax.batch.estonia,0.92,True,2022-11-03T07:00:16,,
cowidev.vax.batch.france,0.45,True,2022-11-03T07:00:17,,
cowidev.vax.batch.germany,1.6,True,2022-11-03T07:00:18,,
cowidev.vax.batch.greece,2.77,True,2022-11-03T07:00:19,,
cowidev.vax.batch.hong_kong,11.98,True,2022-11-03T07:00:29,,
cowidev.vax.batch.indonesia,,,2022-11-03T07:00:17,,
cowidev.vax.batch.ireland,0.43,True,2022-11-03T07:00:17,,
cowidev.vax.batch.israel,7.15,True,2022-11-03T07:00:25,,
cowidev.vax.batch.italy,10.75,True,2022-11-03T07:00:29,,
cowidev.vax.batch.japan,24.69,True,2022-11-03T11:53:07,,
cowidev.vax.batch.jersey,2.01,True,2022-11-03T07:00:27,,
cowidev.vax.batch.latvia,20.43,True,2022-11-03T07:00:47,,
cowidev.vax.batch.lithuania,1.44,True,2022-11-03T07:00:30,,
cowidev.vax.batch.luxembourg,1.38,True,2022-11-03T07:00:30,,
cowidev.vax.batch.malaysia,0.62,True,2022-11-03T07:00:30,,
cowidev.vax.batch.malta,0.85,True,2022-11-03T07:00:30,,
cowidev.vax.batch.netherlands,,,2022-11-03T07:00:30,,
cowidev.vax.batch.new_zealand,7.7,True,2022-11-03T07:00:38,,
cowidev.vax.batch.norway,0.41,True,2022-11-03T07:00:31,,
cowidev.vax.batch.peru,3.93,True,2022-11-03T07:00:34,,
cowidev.vax.batch.portugal,,,2022-11-03T07:00:31,,
cowidev.vax.batch.romania,10.78,True,2022-11-03T07:00:41,,
cowidev.vax.batch.saudi_arabia,10.39,True,2022-11-03T07:00:45,,
cowidev.vax.batch.singapore,2.36,True,2022-11-03T07:00:40,,
cowidev.vax.batch.slovakia,38.71,True,2022-11-03T07:01:19,,
cowidev.vax.batch.slovenia,3.33,True,2022-11-03T07:00:45,,
cowidev.vax.batch.south_korea,34.78,True,2022-11-03T07:01:19,,
cowidev.vax.batch.spc,18.58,True,2022-11-03T07:01:03,,
cowidev.vax.batch.sweden,13.41,True,2022-11-03T07:01:00,,
cowidev.vax.batch.switzerland,21.92,True,2022-11-03T07:01:22,,
cowidev.vax.batch.trinidad_and_tobago,2.21,True,2022-11-03T07:01:06,,
cowidev.vax.batch.ukraine,,,2022-11-03T07:01:06,,
cowidev.vax.batch.united_kingdom,9.11,True,2022-11-03T07:01:15,,
cowidev.vax.batch.united_states,28.26,True,2022-11-03T07:01:43,,
cowidev.vax.batch.uruguay,4.02,True,2022-11-03T07:01:19,,
cowidev.vax.batch.zimbabwe,0.74,True,2022-11-03T07:01:19,,
cowidev.vax.incremental.africacdc,,,2022-11-03T07:01:19,,
cowidev.vax.incremental.antigua_barbuda,,,2022-11-03T07:01:19,,
cowidev.vax.incremental.aruba,1.33,True,2022-11-03T07:01:20,,
cowidev.vax.incremental.azerbaijan,,,2022-11-03T07:01:19,,
cowidev.vax.incremental.bahrain,1.06,True,2022-11-03T07:01:20,,
cowidev.vax.incremental.bangladesh,20.36,True,2022-11-03T07:01:40,,
cowidev.vax.incremental.barbados,,,2022-11-03T07:01:20,,
cowidev.vax.incremental.brazil,0.04,True,2022-11-03T07:01:20,,
cowidev.vax.incremental.bulgaria,0.99,True,2022-11-03T07:01:21,,
cowidev.vax.incremental.china,32.55,True,2022-11-03T07:01:53,,
cowidev.vax.incremental.costa_rica,,,2022-11-03T07:01:21,,
cowidev.vax.incremental.croatia,0.15,True,2022-11-03T07:01:21,,
cowidev.vax.incremental.cuba,2.12,True,2022-11-03T07:01:24,,
cowidev.vax.incremental.curacao,0.35,True,2022-11-03T07:01:23,,
cowidev.vax.incremental.cyprus,0.6,True,2022-11-03T07:01:23,,
cowidev.vax.incremental.dominican_republic,7.84,True,2022-11-03T07:01:31,,
cowidev.vax.incremental.el_salvador,0.59,True,2022-11-03T07:01:24,,
cowidev.vax.incremental.faeroe_islands,0.35,True,2022-11-03T07:01:24,,
cowidev.vax.incremental.fiji,0.0,True,2022-11-03T07:01:24,,
cowidev.vax.incremental.finland,0.25,True,2022-11-03T07:01:25,,
cowidev.vax.incremental.gabon,,,2022-11-03T07:01:25,,
cowidev.vax.incremental.georgia,0.48,True,2022-11-03T07:01:25,,
cowidev.vax.incremental.greenland,1.14,False,2022-11-03T07:04:27,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 74, in main
    Greenland().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 61, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 18, in read
    data = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 22, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 26, in _parse_data_metrics
    dose_1 = clean_count(re.search(r""Innuttaasut ([\d\.]+)"", counters[1].parent.find_all(""dd"")[-1].text).group(1))
IndexError: list index out of range
",list index out of range
cowidev.vax.incremental.guatemala,,,2022-11-03T07:01:27,,
cowidev.vax.incremental.guernsey,0.22,False,2022-11-03T07:04:27,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 61, in main
    Guernsey().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 50, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 15, in read
    df = self.parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 31, in parse_data
    ds.loc[ds[0] == ""Total doses"", 1].values[0].replace(""*"", """"),
IndexError: index 0 is out of bounds for axis 0 with size 0
",index 0 is out of bounds for axis 0 with size 0
cowidev.vax.incremental.hungary,0.89,True,2022-11-03T07:01:29,,
cowidev.vax.incremental.iceland,0.85,True,2022-11-03T07:01:30,,
cowidev.vax.incremental.india,0.87,True,2022-11-03T07:01:31,,
cowidev.vax.incremental.iran,,,2022-11-03T07:01:31,,
cowidev.vax.incremental.isle_of_man,0.83,True,2022-11-03T07:01:32,,
cowidev.vax.incremental.jamaica,7.32,True,2022-11-03T07:01:39,,
cowidev.vax.incremental.kazakhstan,13.1,True,2022-11-03T07:01:45,,
cowidev.vax.incremental.kosovo,2.06,True,2022-11-03T07:01:41,,
cowidev.vax.incremental.kyrgyzstan,1.0,True,2022-11-03T07:01:41,,
cowidev.vax.incremental.laos,3.69,True,2022-11-03T07:01:44,,
cowidev.vax.incremental.macao,21.14,False,2022-11-03T07:04:48,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 86, in main
    Macao().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 72, in export
    data = self.read()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 20, in read
    elem = driver.find_element_by_partial_link_text(""Weekly Bulletin on COVID-19"")
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 462, in find_element_by_partial_link_text
    return self.find_element(by=By.PARTIAL_LINK_TEXT, value=link_text)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""partial link text"",""selector"":""Weekly Bulletin on COVID-19""}
  (Session info: headless chrome=106.0.5249.119)

","Message: no such element: Unable to locate element: {""method"":""partial link text"",""selector"":""Weekly Bulletin on COVID-19""}
  (Session info: headless chrome=106.0.5249.119)
"
cowidev.vax.incremental.moldova,,,2022-11-03T07:01:43,,
cowidev.vax.incremental.monaco,30.38,True,2022-11-03T07:02:13,,
cowidev.vax.incremental.mongolia,0.9,True,2022-11-03T07:01:45,,
cowidev.vax.incremental.montenegro,0.11,True,2022-11-03T07:01:45,,
cowidev.vax.incremental.morocco,,,2022-11-03T07:01:45,,
cowidev.vax.incremental.myanmar,,,2022-11-03T07:01:45,,
cowidev.vax.incremental.nepal,,,2022-11-03T07:01:45,,
cowidev.vax.incremental.north_macedonia,,,2022-11-03T07:01:45,,
cowidev.vax.incremental.northern_cyprus,0.79,True,2022-11-03T07:01:46,,
cowidev.vax.incremental.paho,49.38,True,2022-11-03T11:53:32,,
cowidev.vax.incremental.pakistan,1.43,True,2022-11-03T07:01:47,,
cowidev.vax.incremental.philippines,,,2022-11-03T07:01:47,,
cowidev.vax.incremental.playground_mojmir,4.6,True,2022-11-03T07:01:52,,
cowidev.vax.incremental.poland,0.28,True,2022-11-03T07:01:52,,
cowidev.vax.incremental.qatar,,,2022-11-03T07:01:52,,
cowidev.vax.incremental.russia,0.96,True,2022-11-03T11:52:43,,
cowidev.vax.incremental.saint_lucia,,,2022-11-03T07:01:53,,
cowidev.vax.incremental.serbia,12.25,True,2022-11-03T07:02:05,,
cowidev.vax.incremental.south_africa,5.54,True,2022-11-03T07:01:59,,
cowidev.vax.incremental.spain,11.03,True,2022-11-03T07:02:10,,
cowidev.vax.incremental.sri_lanka,,,2022-11-03T07:02:02,,
cowidev.vax.incremental.suriname,15.19,True,2022-11-03T07:02:17,,
cowidev.vax.incremental.taiwan,6.96,True,2022-11-03T07:02:12,,
cowidev.vax.incremental.thailand,3.61,True,2022-11-03T07:02:13,,
cowidev.vax.incremental.turkey,40.53,False,2022-11-03T11:56:12,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1040, in _validate_conn
    conn.connect()
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fd70e975c90>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 785, in urlopen
    retries = retries.increment(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd70e975c90>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd70e975c90>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd70e975c90>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-11-03T07:02:13,,
cowidev.vax.incremental.vietnam,,,2022-11-03T07:02:13,,
cowidev.vax.incremental.who,4.6,True,2022-11-03T07:02:18,,
cowidev.vax.incremental.zambia,1.52,True,2022-11-03T07:02:15,,
