module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,15.53,True,2022-12-06T07:00:21,,
cowidev.vax.batch.australia,127.35,True,2022-12-06T07:02:13,,
cowidev.vax.batch.austria,14.31,True,2022-12-06T07:00:20,,
cowidev.vax.batch.belgium,15.93,True,2022-12-06T07:00:21,,
cowidev.vax.batch.bolivia,5.42,True,2022-12-06T07:00:11,,
cowidev.vax.batch.canada,29.96,True,2022-12-06T07:00:35,,
cowidev.vax.batch.chile,7.04,True,2022-12-06T07:00:12,,
cowidev.vax.batch.czechia,3.86,True,2022-12-06T07:00:09,,
cowidev.vax.batch.denmark,1.29,False,2022-12-06T07:03:50,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 244, in main
    Denmark().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 225, in export
    df = self.read(index).pipe(self.pipeline, df_current).pipe(self.make_monotonic)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 47, in read
    df = self._load_data(tf)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 59, in _load_data
    df_ss = pd.DataFrame([self._read_single_shots_daily(path)])
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/denmark.py"", line 123, in _read_single_shots_daily
    raise ValueError(f""Unknown vaccine(s) {vaccines_wrong}"")
ValueError: Unknown vaccine(s) {'Uspecificeret'}
",Unknown vaccine(s) {'Uspecificeret'}
cowidev.vax.batch.ecdc,134.46,True,2022-12-06T07:02:20,,
cowidev.vax.batch.ecuador,,,2022-12-06T07:00:05,,
cowidev.vax.batch.estonia,0.59,True,2022-12-06T07:00:06,,
cowidev.vax.batch.france,6.7,True,2022-12-06T07:00:12,,
cowidev.vax.batch.germany,0.35,True,2022-12-06T07:00:06,,
cowidev.vax.batch.greece,17.59,True,2022-12-06T07:00:23,,
cowidev.vax.batch.hong_kong,21.91,True,2022-12-06T07:00:27,,
cowidev.vax.batch.indonesia,,,2022-12-06T07:00:05,,
cowidev.vax.batch.ireland,4.42,True,2022-12-06T07:00:10,,
cowidev.vax.batch.israel,15.8,True,2022-12-06T07:00:21,,
cowidev.vax.batch.italy,10.77,True,2022-12-06T07:00:16,,
cowidev.vax.batch.japan,55.4,True,2022-12-06T07:01:01,,
cowidev.vax.batch.jersey,6.4,True,2022-12-06T07:00:12,,
cowidev.vax.batch.latvia,69.43,True,2022-12-06T07:01:15,,
cowidev.vax.batch.lithuania,5.98,True,2022-12-06T07:00:11,,
cowidev.vax.batch.luxembourg,13.66,True,2022-12-06T07:00:19,,
cowidev.vax.batch.malaysia,1.17,True,2022-12-06T07:00:07,,
cowidev.vax.batch.malta,1.52,True,2022-12-06T07:00:07,,
cowidev.vax.batch.netherlands,,,2022-12-06T07:00:05,,
cowidev.vax.batch.new_zealand,16.57,True,2022-12-06T07:00:22,,
cowidev.vax.batch.norway,0.52,True,2022-12-06T07:00:06,,
cowidev.vax.batch.peru,6.15,True,2022-12-06T07:00:12,,
cowidev.vax.batch.portugal,,,2022-12-06T07:00:05,,
cowidev.vax.batch.romania,52.17,True,2022-12-06T07:00:58,,
cowidev.vax.batch.saudi_arabia,15.34,True,2022-12-06T07:00:21,,
cowidev.vax.batch.singapore,6.2,True,2022-12-06T07:00:12,,
cowidev.vax.batch.slovakia,118.21,True,2022-12-06T07:02:04,,
cowidev.vax.batch.slovenia,3.54,True,2022-12-06T07:00:09,,
cowidev.vax.batch.south_korea,129.48,True,2022-12-06T07:02:15,,
cowidev.vax.batch.spc,30.82,True,2022-12-06T07:00:37,,
cowidev.vax.batch.sweden,26.95,True,2022-12-06T07:00:34,,
cowidev.vax.batch.switzerland,128.76,True,2022-12-06T07:02:18,,
cowidev.vax.batch.trinidad_and_tobago,3.22,True,2022-12-06T07:00:13,,
cowidev.vax.batch.ukraine,,,2022-12-06T07:00:10,,
cowidev.vax.batch.united_kingdom,17.99,True,2022-12-06T07:00:28,,
cowidev.vax.batch.united_states,129.66,True,2022-12-06T07:02:21,,
cowidev.vax.batch.uruguay,9.26,True,2022-12-06T07:00:21,,
cowidev.vax.batch.zimbabwe,3.55,True,2022-12-06T07:00:15,,
cowidev.vax.incremental.africacdc,,,2022-12-06T07:00:12,,
cowidev.vax.incremental.antigua_barbuda,,,2022-12-06T07:00:12,,
cowidev.vax.incremental.aruba,1.48,True,2022-12-06T07:00:13,,
cowidev.vax.incremental.azerbaijan,,,2022-12-06T07:00:12,,
cowidev.vax.incremental.bahrain,9.31,True,2022-12-06T07:00:21,,
cowidev.vax.incremental.bangladesh,38.94,True,2022-12-06T07:00:51,,
cowidev.vax.incremental.barbados,,,2022-12-06T07:00:12,,
cowidev.vax.incremental.brazil,1.44,True,2022-12-06T07:00:14,,
cowidev.vax.incremental.bulgaria,13.86,True,2022-12-06T07:00:27,,
cowidev.vax.incremental.china,30.65,True,2022-12-06T07:04:21,,
cowidev.vax.incremental.costa_rica,,,2022-12-06T07:00:14,,
cowidev.vax.incremental.croatia,1.07,True,2022-12-06T07:00:15,,
cowidev.vax.incremental.cuba,23.97,True,2022-12-06T07:00:39,,
cowidev.vax.incremental.curacao,1.95,True,2022-12-06T07:00:17,,
cowidev.vax.incremental.cyprus,13.3,True,2022-12-06T07:00:30,,
cowidev.vax.incremental.dominican_republic,22.64,False,2022-12-06T07:04:44,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,13.55,True,2022-12-06T07:00:33,,
cowidev.vax.incremental.faeroe_islands,2.63,True,2022-12-06T07:00:22,,
cowidev.vax.incremental.fiji,0.0,True,2022-12-06T07:00:21,,
cowidev.vax.incremental.finland,1.36,True,2022-12-06T07:00:22,,
cowidev.vax.incremental.gabon,,,2022-12-06T07:00:21,,
cowidev.vax.incremental.georgia,9.59,True,2022-12-06T07:00:30,,
cowidev.vax.incremental.greenland,4.78,True,2022-12-06T07:00:26,,
cowidev.vax.incremental.guatemala,,,2022-12-06T07:00:21,,
cowidev.vax.incremental.guernsey,10.7,True,2022-12-06T07:00:32,,
cowidev.vax.incremental.hungary,7.42,True,2022-12-06T07:00:29,,
cowidev.vax.incremental.iceland,4.81,True,2022-12-06T07:00:26,,
cowidev.vax.incremental.india,3.58,True,2022-12-06T07:00:26,,
cowidev.vax.incremental.iran,,,2022-12-06T07:00:22,,
cowidev.vax.incremental.isle_of_man,2.45,True,2022-12-06T07:00:24,,
cowidev.vax.incremental.jamaica,10.67,True,2022-12-06T07:00:33,,
cowidev.vax.incremental.kazakhstan,10.25,True,2022-12-06T07:00:33,,
cowidev.vax.incremental.kosovo,6.69,True,2022-12-06T07:00:31,,
cowidev.vax.incremental.kyrgyzstan,4.9,True,2022-12-06T07:00:30,,
cowidev.vax.incremental.laos,8.04,True,2022-12-06T07:00:34,,
cowidev.vax.incremental.macao,13.05,True,2022-12-06T07:00:39,,
cowidev.vax.incremental.moldova,,,2022-12-06T07:00:27,,
cowidev.vax.incremental.monaco,124.09,True,2022-12-06T07:02:31,,
cowidev.vax.incremental.mongolia,1.37,True,2022-12-06T07:00:29,,
cowidev.vax.incremental.montenegro,1.0,True,2022-12-06T07:00:29,,
cowidev.vax.incremental.morocco,,,2022-12-06T07:00:29,,
cowidev.vax.incremental.myanmar,,,2022-12-06T07:00:29,,
cowidev.vax.incremental.nepal,,,2022-12-06T07:00:29,,
cowidev.vax.incremental.north_macedonia,,,2022-12-06T07:00:29,,
cowidev.vax.incremental.northern_cyprus,5.36,True,2022-12-06T07:00:34,,
cowidev.vax.incremental.paho,137.36,False,2022-12-06T07:07:01,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 64, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 116, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,5.39,True,2022-12-06T07:00:34,,
cowidev.vax.incremental.philippines,,,2022-12-06T07:00:30,,
cowidev.vax.incremental.poland,1.6,True,2022-12-06T07:00:31,,
cowidev.vax.incremental.qatar,,,2022-12-06T07:00:30,,
cowidev.vax.incremental.russia,2.68,True,2022-12-06T07:07:04,,
cowidev.vax.incremental.saint_lucia,,,2022-12-06T07:00:30,,
cowidev.vax.incremental.serbia,12.65,True,2022-12-06T07:00:43,,
cowidev.vax.incremental.south_africa,10.41,True,2022-12-06T07:00:42,,
cowidev.vax.incremental.spain,33.72,True,2022-12-06T07:01:05,,
cowidev.vax.incremental.sri_lanka,,,2022-12-06T07:00:32,,
cowidev.vax.incremental.suriname,15.39,True,2022-12-06T07:00:47,,
cowidev.vax.incremental.taiwan,24.7,True,2022-12-06T07:00:57,,
cowidev.vax.incremental.thailand,9.06,True,2022-12-06T07:00:42,,
cowidev.vax.incremental.turkey,40.04,False,2022-12-06T07:07:44,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    self.sock = conn = self._new_conn()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fcc17742650>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcc17742650>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcc17742650>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcc17742650>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-12-06T07:00:34,,
cowidev.vax.incremental.vietnam,,,2022-12-06T07:00:34,,
cowidev.vax.incremental.who,62.04,True,2022-12-06T07:01:36,,
cowidev.vax.incremental.zambia,1.54,True,2022-12-06T07:00:35,,
