module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,12.86,True,2022-11-24T07:00:18,,
cowidev.vax.batch.australia,,,2022-11-24T07:00:05,,
cowidev.vax.batch.austria,10.87,True,2022-11-24T07:00:16,,
cowidev.vax.batch.belgium,9.64,True,2022-11-24T07:00:15,,
cowidev.vax.batch.bolivia,4.21,True,2022-11-24T07:00:09,,
cowidev.vax.batch.canada,21.49,True,2022-11-24T07:00:27,,
cowidev.vax.batch.chile,1.54,True,2022-11-24T07:00:07,,
cowidev.vax.batch.czechia,2.37,True,2022-11-24T07:00:08,,
cowidev.vax.batch.denmark,78.49,True,2022-11-24T07:01:24,,
cowidev.vax.batch.ecdc,80.67,True,2022-11-24T07:01:26,,
cowidev.vax.batch.ecuador,2.74,True,2022-11-24T07:00:08,,
cowidev.vax.batch.estonia,0.59,True,2022-11-24T07:00:06,,
cowidev.vax.batch.france,5.43,True,2022-11-24T07:00:11,,
cowidev.vax.batch.germany,2.37,True,2022-11-24T07:00:08,,
cowidev.vax.batch.greece,13.06,True,2022-11-24T07:00:18,,
cowidev.vax.batch.hong_kong,16.07,True,2022-11-24T07:00:21,,
cowidev.vax.batch.indonesia,,,2022-11-24T07:00:05,,
cowidev.vax.batch.ireland,4.48,True,2022-11-24T07:00:10,,
cowidev.vax.batch.israel,11.6,True,2022-11-24T07:00:17,,
cowidev.vax.batch.italy,7.88,True,2022-11-24T07:00:13,,
cowidev.vax.batch.japan,55.56,True,2022-11-24T07:01:01,,
cowidev.vax.batch.jersey,4.92,True,2022-11-24T07:00:10,,
cowidev.vax.batch.latvia,48.17,True,2022-11-24T07:00:53,,
cowidev.vax.batch.lithuania,5.93,True,2022-11-24T07:00:11,,
cowidev.vax.batch.luxembourg,4.12,True,2022-11-24T07:00:09,,
cowidev.vax.batch.malaysia,1.06,True,2022-11-24T07:00:06,,
cowidev.vax.batch.malta,1.34,True,2022-11-24T07:00:07,,
cowidev.vax.batch.netherlands,,,2022-11-24T07:00:05,,
cowidev.vax.batch.new_zealand,15.41,True,2022-11-24T07:00:21,,
cowidev.vax.batch.norway,0.48,True,2022-11-24T07:00:06,,
cowidev.vax.batch.peru,4.32,True,2022-11-24T07:00:10,,
cowidev.vax.batch.portugal,,,2022-11-24T07:00:05,,
cowidev.vax.batch.romania,51.45,True,2022-11-24T07:00:57,,
cowidev.vax.batch.saudi_arabia,11.54,True,2022-11-24T07:00:17,,
cowidev.vax.batch.singapore,6.11,True,2022-11-24T07:00:11,,
cowidev.vax.batch.slovakia,65.48,True,2022-11-24T07:01:11,,
cowidev.vax.batch.slovenia,3.74,True,2022-11-24T07:00:10,,
cowidev.vax.batch.south_korea,9.32,True,2022-11-24T09:06:59,,
cowidev.vax.batch.spc,20.47,True,2022-11-24T07:00:27,,
cowidev.vax.batch.sweden,,,2022-11-24T07:00:07,,
cowidev.vax.batch.switzerland,76.71,True,2022-11-24T07:01:23,,
cowidev.vax.batch.trinidad_and_tobago,3.92,True,2022-11-24T07:00:12,,
cowidev.vax.batch.ukraine,,,2022-11-24T07:00:08,,
cowidev.vax.batch.united_kingdom,10.4,True,2022-11-24T07:00:18,,
cowidev.vax.batch.united_states,78.59,True,2022-11-24T07:01:27,,
cowidev.vax.batch.uruguay,6.47,True,2022-11-24T07:00:15,,
cowidev.vax.batch.zimbabwe,7.81,True,2022-11-24T07:00:17,,
cowidev.vax.incremental.africacdc,,,2022-11-24T07:00:09,,
cowidev.vax.incremental.antigua_barbuda,,,2022-11-24T07:00:09,,
cowidev.vax.incremental.aruba,1.16,True,2022-11-24T07:00:11,,
cowidev.vax.incremental.azerbaijan,,,2022-11-24T07:00:10,,
cowidev.vax.incremental.bahrain,6.08,True,2022-11-24T07:00:16,,
cowidev.vax.incremental.bangladesh,37.23,True,2022-11-24T07:00:47,,
cowidev.vax.incremental.barbados,,,2022-11-24T07:00:10,,
cowidev.vax.incremental.brazil,0.83,True,2022-11-24T07:00:11,,
cowidev.vax.incremental.bulgaria,9.09,True,2022-11-24T07:00:19,,
cowidev.vax.incremental.china,262.68,False,2022-11-24T07:08:57,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/china.py"", line 174, in main
    China().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/china.py"", line 161, in export
    df = self.read(df_last.date.max())
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/china.py"", line 40, in read
    with get_driver(options=options, firefox=True, timeout=self.timeout) as driver:
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 159, in get_driver
    driver = webdriver.Firefox(options=options)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py"", line 170, in __init__
    RemoteWebDriver.__init__(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Failed to read marionette port

","Message: Failed to read marionette port
"
cowidev.vax.incremental.costa_rica,,,2022-11-24T07:00:11,,
cowidev.vax.incremental.croatia,0.76,True,2022-11-24T07:00:11,,
cowidev.vax.incremental.cuba,20.22,True,2022-11-24T07:00:31,,
cowidev.vax.incremental.curacao,0.72,True,2022-11-24T07:00:12,,
cowidev.vax.incremental.cyprus,3.61,True,2022-11-24T07:00:15,,
cowidev.vax.incremental.dominican_republic,8.72,False,2022-11-24T07:09:06,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 112, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 91, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 81, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,9.57,True,2022-11-24T07:00:21,,
cowidev.vax.incremental.faeroe_islands,2.59,True,2022-11-24T07:00:14,,
cowidev.vax.incremental.fiji,0.0,True,2022-11-24T07:00:13,,
cowidev.vax.incremental.finland,1.64,True,2022-11-24T07:00:15,,
cowidev.vax.incremental.gabon,,,2022-11-24T07:00:14,,
cowidev.vax.incremental.georgia,6.22,True,2022-11-24T07:00:21,,
cowidev.vax.incremental.greenland,2.18,True,2022-11-24T07:00:17,,
cowidev.vax.incremental.guatemala,,,2022-11-24T07:00:15,,
cowidev.vax.incremental.guernsey,5.21,True,2022-11-24T07:00:20,,
cowidev.vax.incremental.hungary,6.15,True,2022-11-24T07:00:21,,
cowidev.vax.incremental.iceland,1.79,True,2022-11-24T07:00:17,,
cowidev.vax.incremental.india,2.37,True,2022-11-24T07:00:18,,
cowidev.vax.incremental.iran,,,2022-11-24T07:00:16,,
cowidev.vax.incremental.isle_of_man,1.65,True,2022-11-24T07:00:18,,
cowidev.vax.incremental.jamaica,6.92,True,2022-11-24T07:00:24,,
cowidev.vax.incremental.kazakhstan,8.82,True,2022-11-24T07:00:26,,
cowidev.vax.incremental.kosovo,5.77,True,2022-11-24T07:00:23,,
cowidev.vax.incremental.kyrgyzstan,8.93,True,2022-11-24T07:00:26,,
cowidev.vax.incremental.laos,7.88,True,2022-11-24T07:00:25,,
cowidev.vax.incremental.macao,11.54,True,2022-11-24T07:00:29,,
cowidev.vax.incremental.moldova,,,2022-11-24T07:00:18,,
cowidev.vax.incremental.monaco,85.23,True,2022-11-24T07:01:43,,
cowidev.vax.incremental.mongolia,1.22,True,2022-11-24T07:00:19,,
cowidev.vax.incremental.montenegro,0.62,True,2022-11-24T07:00:19,,
cowidev.vax.incremental.morocco,,,2022-11-24T07:00:18,,
cowidev.vax.incremental.myanmar,,,2022-11-24T07:00:18,,
cowidev.vax.incremental.nepal,,,2022-11-24T07:00:18,,
cowidev.vax.incremental.north_macedonia,,,2022-11-24T07:00:18,,
cowidev.vax.incremental.northern_cyprus,5.21,True,2022-11-24T07:00:23,,
cowidev.vax.incremental.paho,113.4,False,2022-11-24T07:10:59,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 57, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 114, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,4.98,True,2022-11-24T07:00:24,,
cowidev.vax.incremental.philippines,,,2022-11-24T07:00:19,,
cowidev.vax.incremental.playground_mojmir,4.67,True,2022-11-24T07:00:24,,
cowidev.vax.incremental.poland,1.25,True,2022-11-24T07:00:21,,
cowidev.vax.incremental.qatar,,,2022-11-24T07:00:21,,
cowidev.vax.incremental.russia,49.15,True,2022-11-24T07:01:10,,
cowidev.vax.incremental.saint_lucia,,,2022-11-24T07:00:21,,
cowidev.vax.incremental.serbia,6.88,True,2022-11-24T07:00:28,,
cowidev.vax.incremental.south_africa,10.51,True,2022-11-24T07:00:32,,
cowidev.vax.incremental.spain,26.31,True,2022-11-24T07:00:47,,
cowidev.vax.incremental.sri_lanka,,,2022-11-24T07:00:21,,
cowidev.vax.incremental.suriname,17.18,True,2022-11-24T07:00:38,,
cowidev.vax.incremental.taiwan,13.03,True,2022-11-24T07:00:34,,
cowidev.vax.incremental.thailand,5.28,True,2022-11-24T07:00:27,,
cowidev.vax.incremental.turkey,40.03,False,2022-11-24T07:11:39,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    self.sock = conn = self._new_conn()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f56ca353190>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f56ca353190>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f56ca353190>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f56ca353190>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-11-24T07:00:23,,
cowidev.vax.incremental.vietnam,,,2022-11-24T07:00:23,,
cowidev.vax.incremental.who,47.74,True,2022-11-24T07:01:11,,
cowidev.vax.incremental.zambia,1.44,True,2022-11-24T07:00:25,,
