module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,16.84,True,2022-12-31T07:00:23,,
cowidev.vax.batch.australia,127.11,True,2022-12-31T07:02:13,,
cowidev.vax.batch.austria,15.65,True,2022-12-31T07:00:22,,
cowidev.vax.batch.belgium,7.55,True,2022-12-31T07:00:14,,
cowidev.vax.batch.bolivia,4.33,True,2022-12-31T07:00:11,,
cowidev.vax.batch.canada,33.5,True,2022-12-31T07:00:40,,
cowidev.vax.batch.chile,0.86,True,2022-12-31T07:00:07,,
cowidev.vax.batch.czechia,43.44,True,2022-12-31T07:00:50,,
cowidev.vax.batch.denmark,132.29,True,2022-12-31T07:02:19,,
cowidev.vax.batch.ecdc,136.73,True,2022-12-31T07:02:23,,
cowidev.vax.batch.ecuador,,,2022-12-31T07:00:06,,
cowidev.vax.batch.estonia,0.57,True,2022-12-31T07:00:07,,
cowidev.vax.batch.france,7.49,True,2022-12-31T07:00:14,,
cowidev.vax.batch.germany,0.17,True,2022-12-31T07:00:06,,
cowidev.vax.batch.greece,21.15,True,2022-12-31T07:00:27,,
cowidev.vax.batch.hong_kong,23.1,True,2022-12-31T07:00:29,,
cowidev.vax.batch.indonesia,,,2022-12-31T07:00:06,,
cowidev.vax.batch.ireland,4.78,True,2022-12-31T07:00:11,,
cowidev.vax.batch.israel,16.37,True,2022-12-31T07:00:23,,
cowidev.vax.batch.italy,11.41,True,2022-12-31T07:00:18,,
cowidev.vax.batch.japan,55.9,True,2022-12-31T07:01:02,,
cowidev.vax.batch.jersey,5.78,True,2022-12-31T07:00:12,,
cowidev.vax.batch.latvia,72.9,True,2022-12-31T07:01:19,,
cowidev.vax.batch.lithuania,5.99,True,2022-12-31T07:00:12,,
cowidev.vax.batch.luxembourg,3.34,True,2022-12-31T07:00:10,,
cowidev.vax.batch.malaysia,0.72,True,2022-12-31T07:00:07,,
cowidev.vax.batch.malta,1.09,True,2022-12-31T07:00:07,,
cowidev.vax.batch.netherlands,,,2022-12-31T07:00:06,,
cowidev.vax.batch.new_zealand,16.4,True,2022-12-31T07:00:23,,
cowidev.vax.batch.norway,0.9,True,2022-12-31T07:00:07,,
cowidev.vax.batch.peru,4.91,True,2022-12-31T07:00:11,,
cowidev.vax.batch.portugal,,,2022-12-31T07:00:06,,
cowidev.vax.batch.romania,56.51,True,2022-12-31T07:01:03,,
cowidev.vax.batch.saudi_arabia,15.24,True,2022-12-31T07:00:21,,
cowidev.vax.batch.singapore,4.51,True,2022-12-31T07:00:11,,
cowidev.vax.batch.slovakia,112.01,True,2022-12-31T07:01:58,,
cowidev.vax.batch.slovenia,3.47,True,2022-12-31T07:00:10,,
cowidev.vax.batch.south_korea,115.15,True,2022-12-31T07:02:02,,
cowidev.vax.batch.spc,29.1,True,2022-12-31T07:00:36,,
cowidev.vax.batch.sweden,20.77,True,2022-12-31T07:00:28,,
cowidev.vax.batch.switzerland,133.84,True,2022-12-31T07:02:21,,
cowidev.vax.batch.trinidad_and_tobago,3.96,True,2022-12-31T07:00:14,,
cowidev.vax.batch.ukraine,,,2022-12-31T07:00:10,,
cowidev.vax.batch.united_kingdom,19.3,True,2022-12-31T07:00:30,,
cowidev.vax.batch.united_states,133.15,True,2022-12-31T07:02:24,,
cowidev.vax.batch.uruguay,10.24,True,2022-12-31T07:00:21,,
cowidev.vax.batch.zimbabwe,1.99,True,2022-12-31T07:00:13,,
cowidev.vax.incremental.africacdc,,,2022-12-31T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2022-12-31T07:00:11,,
cowidev.vax.incremental.aruba,1.8,True,2022-12-31T07:00:13,,
cowidev.vax.incremental.azerbaijan,,,2022-12-31T07:00:12,,
cowidev.vax.incremental.bahrain,,,2022-12-31T07:00:12,,
cowidev.vax.incremental.bangladesh,39.07,True,2022-12-31T07:00:51,,
cowidev.vax.incremental.barbados,,,2022-12-31T07:00:12,,
cowidev.vax.incremental.brazil,1.41,True,2022-12-31T07:00:14,,
cowidev.vax.incremental.bulgaria,12.82,True,2022-12-31T07:00:26,,
cowidev.vax.incremental.china,25.4,True,2022-12-31T07:00:38,,
cowidev.vax.incremental.costa_rica,,,2022-12-31T07:00:14,,
cowidev.vax.incremental.croatia,1.5,True,2022-12-31T07:00:15,,
cowidev.vax.incremental.cuba,23.45,True,2022-12-31T07:00:37,,
cowidev.vax.incremental.curacao,1.27,True,2022-12-31T07:00:15,,
cowidev.vax.incremental.cyprus,3.57,True,2022-12-31T07:00:17,,
cowidev.vax.incremental.dominican_republic,22.81,False,2022-12-31T07:04:14,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,16.48,True,2022-12-31T07:00:31,,
cowidev.vax.incremental.faeroe_islands,2.21,True,2022-12-31T07:00:20,,
cowidev.vax.incremental.fiji,0.0,True,2022-12-31T07:00:18,,
cowidev.vax.incremental.finland,0.81,True,2022-12-31T07:00:18,,
cowidev.vax.incremental.gabon,,,2022-12-31T07:00:18,,
cowidev.vax.incremental.georgia,10.49,True,2022-12-31T07:00:29,,
cowidev.vax.incremental.greenland,5.35,True,2022-12-31T07:00:25,,
cowidev.vax.incremental.guatemala,,,2022-12-31T07:00:21,,
cowidev.vax.incremental.guernsey,12.21,True,2022-12-31T07:00:33,,
cowidev.vax.incremental.hungary,6.82,True,2022-12-31T07:00:28,,
cowidev.vax.incremental.iceland,5.1,True,2022-12-31T07:00:27,,
cowidev.vax.incremental.india,3.17,True,2022-12-31T07:00:26,,
cowidev.vax.incremental.iran,,,2022-12-31T07:00:23,,
cowidev.vax.incremental.isle_of_man,2.36,True,2022-12-31T07:00:25,,
cowidev.vax.incremental.jamaica,9.79,True,2022-12-31T07:00:33,,
cowidev.vax.incremental.kazakhstan,8.61,True,2022-12-31T07:00:34,,
cowidev.vax.incremental.kosovo,7.68,True,2022-12-31T07:00:33,,
cowidev.vax.incremental.kyrgyzstan,5.26,True,2022-12-31T07:00:31,,
cowidev.vax.incremental.laos,7.91,True,2022-12-31T07:00:34,,
cowidev.vax.incremental.macao,11.71,True,2022-12-31T07:00:39,,
cowidev.vax.incremental.moldova,,,2022-12-31T07:00:27,,
cowidev.vax.incremental.monaco,125.03,True,2022-12-31T07:02:32,,
cowidev.vax.incremental.mongolia,1.62,True,2022-12-31T07:00:30,,
cowidev.vax.incremental.montenegro,1.07,True,2022-12-31T07:00:29,,
cowidev.vax.incremental.morocco,,,2022-12-31T07:00:29,,
cowidev.vax.incremental.myanmar,,,2022-12-31T07:00:29,,
cowidev.vax.incremental.nepal,,,2022-12-31T07:00:29,,
cowidev.vax.incremental.north_macedonia,,,2022-12-31T07:00:29,,
cowidev.vax.incremental.northern_cyprus,4.12,True,2022-12-31T07:00:33,,
cowidev.vax.incremental.paho,138.04,False,2022-12-31T07:06:32,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 64, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 116, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,,,2022-12-31T07:00:29,,
cowidev.vax.incremental.philippines,,,2022-12-31T07:00:29,,
cowidev.vax.incremental.poland,1.69,True,2022-12-31T07:00:31,,
cowidev.vax.incremental.qatar,,,2022-12-31T07:00:30,,
cowidev.vax.incremental.russia,36.84,True,2022-12-31T07:01:06,,
cowidev.vax.incremental.saint_lucia,,,2022-12-31T07:00:30,,
cowidev.vax.incremental.serbia,0.37,False,2022-12-31T07:06:32,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 88, in main
    Serbia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 74, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 23, in read
    soup = get_soup(self.source_url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
",Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
cowidev.vax.incremental.south_africa,,,2022-12-31T07:00:31,,
cowidev.vax.incremental.spain,29.16,True,2022-12-31T07:01:00,,
cowidev.vax.incremental.sri_lanka,,,2022-12-31T07:00:31,,
cowidev.vax.incremental.suriname,16.08,True,2022-12-31T07:00:47,,
cowidev.vax.incremental.taiwan,25.54,True,2022-12-31T07:00:57,,
cowidev.vax.incremental.thailand,7.89,True,2022-12-31T07:00:39,,
cowidev.vax.incremental.turkey,40.04,False,2022-12-31T07:07:12,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    self.sock = conn = self._new_conn()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f82eda6c730>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f82eda6c730>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f82eda6c730>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f82eda6c730>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-12-31T07:00:33,,
cowidev.vax.incremental.vietnam,,,2022-12-31T07:00:33,,
cowidev.vax.incremental.who,68.87,True,2022-12-31T07:01:42,,
cowidev.vax.incremental.zambia,1.45,True,2022-12-31T07:00:34,,
